# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 700)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono Light")
        font.setPointSize(16)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loadout1_title = QtWidgets.QLabel(self.centralwidget)
        self.loadout1_title.setGeometry(QtCore.QRect(20, 20, 620, 21))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono ExtraLight")
        font.setPointSize(16)
        self.loadout1_title.setFont(font)
        self.loadout1_title.setObjectName("loadout1_title")
        self.loadout1_weapons = QtWidgets.QLabel(self.centralwidget)
        self.loadout1_weapons.setGeometry(QtCore.QRect(20, 40, 760, 30))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono ExtraBold")
        font.setPointSize(20)
        self.loadout1_weapons.setFont(font)
        self.loadout1_weapons.setAlignment(QtCore.Qt.AlignCenter)
        self.loadout1_weapons.setObjectName("loadout1_weapons")
        self.loadout1_stats = QtWidgets.QLabel(self.centralwidget)
        self.loadout1_stats.setGeometry(QtCore.QRect(20, 80, 760, 20))
        self.loadout1_stats.setAlignment(QtCore.Qt.AlignCenter)
        self.loadout1_stats.setObjectName("loadout1_stats")
        self.loadout2_stats = QtWidgets.QLabel(self.centralwidget)
        self.loadout2_stats.setGeometry(QtCore.QRect(20, 380, 760, 20))
        self.loadout2_stats.setAlignment(QtCore.Qt.AlignCenter)
        self.loadout2_stats.setObjectName("loadout2_stats")
        self.loadout2_title = QtWidgets.QLabel(self.centralwidget)
        self.loadout2_title.setGeometry(QtCore.QRect(20, 320, 620, 21))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono ExtraLight")
        font.setPointSize(16)
        self.loadout2_title.setFont(font)
        self.loadout2_title.setObjectName("loadout2_title")
        self.loadout2_weapons = QtWidgets.QLabel(self.centralwidget)
        self.loadout2_weapons.setGeometry(QtCore.QRect(20, 340, 760, 30))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono ExtraBold")
        font.setPointSize(20)
        self.loadout2_weapons.setFont(font)
        self.loadout2_weapons.setAlignment(QtCore.Qt.AlignCenter)
        self.loadout2_weapons.setObjectName("loadout2_weapons")
        self.regenerate_button = QtWidgets.QPushButton(self.centralwidget)
        self.regenerate_button.setGeometry(QtCore.QRect(20, 610, 760, 80))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono Light")
        font.setPointSize(42)
        self.regenerate_button.setFont(font)
        self.regenerate_button.setObjectName("regenerate_button")
        self.loadout1_weapon1 = QtWidgets.QLabel(self.centralwidget)
        self.loadout1_weapon1.setGeometry(QtCore.QRect(100, 110, 300, 200))
        self.loadout1_weapon1.setText("")
        self.loadout1_weapon1.setPixmap(QtGui.QPixmap("../images/Bocek Compound Bow.png"))
        self.loadout1_weapon1.setAlignment(QtCore.Qt.AlignCenter)
        self.loadout1_weapon1.setObjectName("loadout1_weapon1")
        self.loadout1_weapon2 = QtWidgets.QLabel(self.centralwidget)
        self.loadout1_weapon2.setGeometry(QtCore.QRect(400, 110, 300, 200))
        self.loadout1_weapon2.setText("")
        self.loadout1_weapon2.setPixmap(QtGui.QPixmap("../images/Bocek Compound Bow.png"))
        self.loadout1_weapon2.setAlignment(QtCore.Qt.AlignCenter)
        self.loadout1_weapon2.setObjectName("loadout1_weapon2")
        self.loadout2_weapon1 = QtWidgets.QLabel(self.centralwidget)
        self.loadout2_weapon1.setGeometry(QtCore.QRect(100, 410, 300, 200))
        self.loadout2_weapon1.setText("")
        self.loadout2_weapon1.setPixmap(QtGui.QPixmap("../images/Bocek Compound Bow.png"))
        self.loadout2_weapon1.setAlignment(QtCore.Qt.AlignCenter)
        self.loadout2_weapon1.setObjectName("loadout2_weapon1")
        self.loadout2_weapon2 = QtWidgets.QLabel(self.centralwidget)
        self.loadout2_weapon2.setGeometry(QtCore.QRect(400, 410, 300, 200))
        self.loadout2_weapon2.setText("")
        self.loadout2_weapon2.setPixmap(QtGui.QPixmap("../images/Bocek Compound Bow.png"))
        self.loadout2_weapon2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.loadout2_weapon2.setObjectName("loadout2_weapon2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Apex Randomiser"))
        self.loadout1_title.setText(_translate("MainWindow", "Loadout #1"))
        self.loadout1_weapons.setText(_translate("MainWindow", "Bocek Compound Bow | Bocek Compound Bow"))
        self.loadout1_stats.setText(_translate("MainWindow", "DPS: 107 - B Tier | DPS: 107 - B Tier"))
        self.loadout2_stats.setText(_translate("MainWindow", "DPS: 107 - B Tier | DPS: 107 - B Tier"))
        self.loadout2_title.setText(_translate("MainWindow", "Loadout #1"))
        self.loadout2_weapons.setText(_translate("MainWindow", "Bocek Compound Bow | Bocek Compound Bow"))
        self.regenerate_button.setText(_translate("MainWindow", "Generate new loadouts"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
